### ISSUE TITLE
Set up Context in Next.js to store values selected from dropdown boxes

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#100]
**Context**
Our old method to store values through the application was via passing values through a query string between React components. We will attempt to store values in React Context to prevent passing values down manually through each component.

**Task**
- Set up new relevant files to initialise React Context
- Edit necessary files to wrap our application with Context
- Attempt storage of one value and test functionality

**Figma Link**
None

**Acceptance Criteria**
Successful storage of one value in context

**Comment by ryhuz** [comment]
#103
