### ISSUE TITLE
(BUG) Disable all areas below the Address box, until an address has been selected

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#105]
**Context**
Currently you can access the item/method boxes with the address not filled.
![photo_6233425606398293438_x](https://user-images.githubusercontent.com/79783660/196721552-52ac5dea-3f03-42e2-93cf-2e6fc5855390.jpg)

**Task**
- Ensure all items below the address input box is disabled before any address has been inputted - this means the text should be of gray color (you can choose a standard hexcode for gray) and input boxes should not pop out options. 
- The "+" button should be disabled as well.

**Figma Link**
https://www.figma.com/file/kN115h4H1jk797qa3x08Et/RGW-Design_Master-Design-File?node-id=3458%3A21137

**Acceptance Criteria**
Working endpoint to read from (test in local)

**Comment by ryhuz** [comment]
i actually think it's better to disable the `where to recycle` button and flag out missing address on blur.

this is because if user keys in address, then adds a few items, then removes address, all the items will be disabled which is weird
