### ISSUE TITLE
"Recommended" popup on hover

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#113]
**Context**
We want a popup to warn users about the contamination of recyclables.
![image](https://user-images.githubusercontent.com/79783660/216829601-61450946-3164-4415-b31f-09621b229f74.png)

**Task**
- Upon hovering on "Recommended", this popup should show.

**Figma Link**
https://www.figma.com/file/kN115h4H1jk797qa3x08Et/RGW-Design_Master-Design-File?node-id=4026%3A21461&t=IeCS7KeogxbXAkXh-0
**Acceptance Criteria**
npm run build works

**Comment by zhenhao1886** [comment]
Changed the import path
