### ISSUE TITLE
(Cont. from #119) Instantiate "Instructions Page" structure

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#116]
**Context**
Upon clicking the "How to recycle?" button, users are brought to this page. It is a series of dropdowns that showcase the method to handle each item, and a restart button.

The dropdown should nest a carousel in it to rotate between the necessary information (when there is >1 page)
![image](https://user-images.githubusercontent.com/79783660/220843684-7c2e5b0c-be44-4578-ac29-ac16ac510734.png)

**Task**
- Set up the page when state = 1
- Create the general look of the first mockup (see image above leftmost)
- Instantiate dropdowns based on # of items stored in context (and add condition tags if able)

**Figma Link**
https://www.figma.com/file/kN115h4H1jk797qa3x08Et/RGW-Design_Master-Design-File?node-id=4113%3A22184&t=0hEzB95UEwJJ0Apa-0

**Acceptance Criteria**
npm run build works
Basic structure of page

**Comment by itswolv3** [comment]
Completed a base of this page, was struggling with the footer, if I could get some help on it, would be appreciated.
