### ISSUE TITLE
Backend: Reverse geolocate the postal code for each blue bin

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#125]
**Context/Task**
In our backend google sheets, we have the postal code of all recycling bins. However, we want to reverse geolocate them such that we can get the actual address of each postal code. 
- Convert postal codes into addresses using some framework (eg. Google Map API but its paid...)

**Figma Link**
- NIL

**Acceptance Criteria**
- NIL

**Comment by ruthondrada** [comment]
Hey @neozhixuan ,

Can I check with you if my assumption is correct?

1. We are going to add `address` under `facilities list` tab.
2. Are we going to do them manually? or by code? - since i'm not familiar with the repo yet, would be nice if you could point out which file(s) to look at if it's gonna be done by code. 

Thanks!

**Comment by neozhixuan** [comment]
Hey @ruthondrada,

1. Yes it is under the address column in the google sheets.
2. We can utilise a reverse geolocation library in a coding platform like jupyter notebook to do it computationally. E.g. download this Facilities List table, run the current postcode column through a reverse geolocation function, and get the respective address.

e.g. 469662 -> 11 Bedok North Singapore ...
![image](https://github.com/bettersg/recyclegowhere/assets/79783660/00fef893-d2a8-4569-a72a-43803f0ee8ff)

**Comment by neozhixuan** [comment]
Sure, as long as the API limit doesn’t stop you from successfully reverse geolocation

**Comment by ruthondrada** [comment]
thanks!  i notice that there's longtiude and latitude already.

Supposed i finished it this week, Do i just paste the postal code? or how dowe go about it?

**Comment by neozhixuan** [comment]
Yep, just make sure the address is in the format of the current sheet entries!

**Comment by ruthondrada** [comment]
hey @neozhixuan ,

i manage to have the python code running - just left with writing it on the excel sheet.
i used the onemap api as it is more accurate.

Also, i cannot write / over write in google sheet and i prefer not too as i think it's best if it's reviewed.
I'll attached the file her once done!

thanks!

**Comment by ruthondrada** [comment]
[RecycleGoWhere Backend.xlsx](https://github.com/bettersg/recyclegowhere/files/13035499/RecycleGoWhere.Backend.xlsx)

@neozhixuan , updated the the address under `new_address` btw please take note of the following

1. there are some address that the api cannot be found (196 of them), can filter by `Address not found`
2. There is one entry that has empty postal code,
