### ISSUE TITLE
Landing Page: change display of the footer buttons

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#143]
**Context/Task**
Based on UX changes, the sticky footer will have an upgraded design.

**Figma Link**
https://www.figma.com/file/kN115h4H1jk797qa3x08Et/RGW-Design_Master-Design-File?type=design&node-id=4685-30668&t=vDm0KEqN0T4tGb7y-0

**Acceptance Criteria**
npm run build works

**Comment by ryhuz** [comment]
i think will be good to split this into 2 tickets
1. change the order
2. change the footer
