### ISSUE TITLE
Uncle Semaku Image broken mobile - Tested

### ISSUE THREAD

**Issue by itswolv3** [bettersg/recyclegowhere#43]
# Broken image link on mobile. Image loads and displays fine desktop.
Should be an easy fix.

## Broken image
![Uncle Semakau Missing](https://user-images.githubusercontent.com/65454356/157741114-02a2969a-95b1-4aa5-b156-9d7f5b3daf01.png)
## Error
![uncle semakau erro](https://user-images.githubusercontent.com/65454356/157741152-2341d450-87a1-4d8a-8a27-1e8afc61dcfc.png)

**Comment by itswolv3** [comment]
Loads on: How would you like to take action.

**Comment by ryhuz** [comment]
responsiveness issue. looking into Next/Image docs
