### ISSUE TITLE
No indication that no valid facilities found for non-blue bin items - UX input?

### ISSUE THREAD

**Issue by ryhuz** [bettersg/recyclegowhere#53]
`issue converted - please view comments below for updates`

Found an error while cleaning up/refactoring Geolocation

Steps to reproduce

1. on the deployed site, choose non-blue bin things (toys)
2. in need of repair
3. self-disposal
4. error

due to being unable to find locations that corresponds to the item and condition

to fix after Geolocation clean up

**Comment by ryhuz** [comment]
the error is fixed by #73 - if there are no facilities, there will be no markers showing up

converting this to a different issue where there is no indication to the user that no facilities were found

**Comment by neozhixuan** [comment]
This might be similar to #32 actually!

**Comment by ryhuz** [comment]
closing as similar to #32
