### ISSUE TITLE
iOS unable to autofill addresses in the search bar

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#66]
iOS has the function to autofill addresses when you type from its memory. However when you autofill, the multiselect stays blank.

**Comment by itswolv3** [comment]
Tested and confirmed this is a Safari issue, tested Chrome, Brave, Firefox on OSX and iOS autofill works. Exploring possible issues with code and Safari.

**Comment by itswolv3** [comment]
Underlining issue is a variable
![Screenshot 2022-03-29 at 21 12 34](https://user-images.githubusercontent.com/65454356/160691393-bb0f698b-7db5-43b9-826c-834cd7f3e266.png)
