### ISSUE TITLE
Initiate the skeleton of the main page based on the archive

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#82]
**Context**
Upon reinitialising the project with typescript files, we will have an basic index.js file for the landing page. Attached below is the design we have planned to be developed.
![image](https://user-images.githubusercontent.com/79783660/174634863-846c2539-35e9-41ae-bed8-fbea4e62b37e.png)
https://www.figma.com/file/kN115h4H1jk797qa3x08Et/RGW-Design_Master-Design-File?node-id=2843%3A18118

**Task**
The task here is to create the general structure (navbar, logo, words, basic multiselect box, 2 buttons at the bottom of the page)

**Timeline**
Follow figma timeline

**Acceptance Criteria**
Runs properly after npm run dev and push to main

**Comment by ryhuz** [comment]
have submitted a PR of a skeleton landing page, with no reference to the items or conditions - these can be added in later

the functionality of adding and removing lines is there, with the state being hoisted. This should allow the selection to be eventually held in a `Context` and passed to the next page

**Comment by ryhuz** [comment]
added OneMapApi and debounce for #80
