### ISSUE TITLE
Containerise the center of the laptop landing site

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#93]
**Context**
![image](https://user-images.githubusercontent.com/79783660/189701608-53179f4f-3741-4059-9b94-95c156cf9b11.png)
The laptop website has a full screen width, we want it to be similar to google's landing page width.

**Task**
- Set up a container around the main components to limit the components to a certain width, in laptop version

**Figma Link**

**Acceptance Criteria**
Runs in npm run dev

**Comment by ryhuz** [comment]
fixed by #90
