### ISSUE TITLE
Set up stationary footer such that it does not overlap the main components

### ISSUE THREAD

**Issue by neozhixuan** [bettersg/recyclegowhere#94]
**Context**
The footer now overlaps with the top components (item + method boxes). We need to separate top and bottom, as suggested by Shawn - such that the top is scrolling and bottom is fixed.

**Task**
- Maintain a stationary footer with the same buttons
- Top area should not intersect with the footer 
- Item + method lists should be scrollable 

**Figma Link**
https://www.figma.com/proto/kN115h4H1jk797qa3x08Et/RGW-Design_Master-Design-File?node-id=3458%3A20836&scaling=min-zoom&page-id=2738%3A17735&starting-point-node-id=3408%3A20879

**Acceptance Criteria**
Runs in npm run dev

**Comment by ryhuz** [comment]
#90 fixed here
